### PR TITLE
Revert knex dependency version, upgrade objection version

### PR DESCRIPTION
**Pull request by zanechua**
Objection does not support knex `0.95.x`.

Reverting the dependency for this until it's resolved in https://github.com/Vincit/objection.js/issues/2012

### CODE REVIEW

**Comment by zanechua** [comment]
@jarcodallo can you please backport this for 0.4.x since it shouldn't have been bumped in the first place?

**Comment by jarcodallo** [comment]
> @jarcodallo can you please backport this for 0.4.x since it shouldn't have been bumped in the first place?

I will release a major version with the fix.

**Comment by jarcodallo** [comment]
@zanechua please try with 1.0.0 https://github.com/jarcodallo/fastify-objectionjs/releases/tag/v1.0.0

**Comment by zanechua** [comment]
It's not really for me but for people who want to use objection v2 so they'll have to stick to the 0.4 version. And they should not be having knex pegged to 0.95.

**Comment by jarcodallo** [comment]
> It's not really for me but for people who want to use objection v2 so they'll have to stick to the 0.4 version. And they should not be having knex pegged to 0.95.

Oh! I see. I can make a new version with a lower knex.

**Pull request closed without merging**
